### ISSUE TITLE
Pick and place using baxter

### ISSUE THREAD

**Issue by arunavanag591** [ros-aldebaran/romeo_moveit_actions#4]
Hello I want to perform a pick and place of coke can with baxter. I am using ORK to recognize and find its position. I came across your package for romeo.

Could you please tell me how you define this parameters. How can i get these for baxter? Any help will be appreciated.:

```
`if (robot_name_ == "nao")
{
  block_size = 0.01;
  pose_default.position.x = 0.2;
  pose_default.position.y = 0.1;
  pose_default.position.z = 0.0;
  pose_default_r = pose_default;
  pose_default_r.position.y *= -1;

  if (test_step_ == 0.0)
    test_step_ = 0.03;
  if (x_min_ == 0.0)
    x_min_ = 0.1; //0.3;
  if (x_max_ == 0.0)
    x_max_ = 0.21;
  if (y_min_ == 0.0)
    y_min_ = 0.12;
  if (y_max_ == 0.0)
    y_max_ = 0.24;
  if (z_min_ == 0.0)
    z_min_ = -0.07;
  if (z_max_ == 0.0)
    z_max_ = +0.05;
}`
```

**Comment by nlyubova** [comment]
hello, this is just an initialisation of an object position to grasp. This position should be updated by the position of the detected object

**Comment by nlyubova** [comment]
it is better to check the PR2 demo
