### ISSUE TITLE
Planning time doesn't change

### ISSUE THREAD

**Issue by lluissalord** [ros-aldebaran/romeo_moveit_actions#6]
I have tested to change the planning time with `move_group->setPlanningTime(planning_time)` before calling to make the plan, but it's seems that always use a planning time of 30 seconds.
May be it should not be here and report it to the `move_group_interface` package, but currently I don't know if may be I'm missing something.

State that I tested inside the action.cpp file.

Thank you,
Lluis

**Comment by lluissalord** [comment]
Now I see that depends on which computer I'm using. Because the same package and executing in the same way one use the fixed timing of 30 sec and the other use the one specified.

**Comment by nlyubova** [comment]
did you use the same MoveIt version? and this package from source, right?

**Comment by lluissalord** [comment]
Sorry, today I saw that now it's working well. I don't know what happend.

The impressive thing is that it seems that with one computer I can have much better results (solutions with an smaller tolerance) than with the other. In some days I will publish my TFM in my repo [romeo_grasper](https://github.com/lluissalord/romeo_grasper) where this is shown with other things that may be are interesting for you @nlyubova.

So I can close the issue if you want.
Thank you

**Comment by nlyubova** [comment]
Great. I've also got very different results with different planning timeand with larger time prediction was better, but it took longer time. Very interesting to know your results! And videos!
